
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80           # External port (accessible to clients)
      targetPort: 3000   # Port inside the container
  type: LoadBalancer     # Use NodePort or ClusterIP if LoadBalancer isn't available
