apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
  labels:
    app: hotel-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
        - name: hotel-service
          image: your-docker-username/hotel-service:latest
          ports:
            - containerPort: 50052
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/hotel
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-service
spec:
  selector:
    app: hotel-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50052
  type: ClusterIP
